FROM maven:3.8-jdk-8-slim AS dep-cache
WORKDIR /opt
COPY ./pom.xml /opt/pom.xml
COPY ./connector/pom.xml /opt/connector/pom.xml
COPY ./sample/pom.xml /opt/sample/pom.xml
RUN mvn -B -f ./pom.xml -pl connector dependency:go-offline

FROM dep-cache AS builder
WORKDIR /opt
COPY ./connector/src /opt/connector/src
COPY ./sample/src /opt/sample/src
RUN mvn install -Dmaven.test.skip

FROM flink:1.15.2-scala_2.12-java8
COPY --from=builder /opt/sample/target/sample-*.jar /opt/flink/usrlib/sample.jar
COPY --from=builder /opt/connector/target/flink-questdb-connector-*.jar /opt/flink/lib/flink-questdb-connector.jar

RUN echo "pipeline.time-characteristic: EventTime" >> /opt/flink/conf/flink-conf.yaml; \
    echo "taskmanager.memory.jvm-metaspace.size: 256m" >> /opt/flink/conf/flink-conf.yaml;
