FROM maven:3.8-jdk-8-slim AS dep-cache
WORKDIR /opt
COPY ./pom.xml /opt/pom.xml
COPY ./connector/pom.xml /opt/connector/pom.xml
COPY ./samples/pom.xml /opt/samples/pom.xml
COPY ./samples/coinbase-to-kafka-to-questdb/pom.xml /opt/samples/coinbase-to-kafka-to-questdb/pom.xml
COPY ./samples/datagen-to-questdb/pom.xml /opt/samples/datagen-to-questdb/pom.xml
RUN mvn -B -f ./pom.xml -pl connector dependency:go-offline

FROM dep-cache AS builder
WORKDIR /opt
COPY ./connector/src /opt/connector/src
COPY ./samples/coinbase-to-kafka-to-questdb/src /opt/samples/coinbase-to-kafka-to-questdb/src
COPY ./samples/datagen-to-questdb/src /opt/samples/datagen-to-questdb/src
RUN mvn install -Dmaven.test.skip

FROM flink:1.15.2-scala_2.12-java8
RUN wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/1.15.2/flink-sql-connector-kafka-1.15.2.jar
COPY --from=builder /opt/samples/coinbase-to-kafka-to-questdb/target/coinbase-to-kafka-to-questdb-*.jar /opt/flink/usrlib/coinbase-to-kafka-to-questdb.jar
COPY --from=builder /opt/connector/target/flink-questdb-connector-*.jar /opt/flink/lib/flink-questdb-connector.jar

RUN echo "pipeline.time-characteristic: EventTime" >> /opt/flink/conf/flink-conf.yaml; \
    echo "taskmanager.memory.jvm-metaspace.size: 256m" >> /opt/flink/conf/flink-conf.yaml;
