version: '2.1'
services:
  jobmanager:
    image: questdb-flink-sample
    build:
      dockerfile: ./Dockerfile-Samples
      context: ./../
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8082:8081"
    command: standalone-job
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    depends_on:
      - questdb
  taskmanager:
    image: questdb-flink-sample
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  questdb:
    image: questdb/questdb:6.5.2
    expose:
      - "9009"
    ports:
      - "19000:9000"
    environment:
      - QDB_CAIRO_COMMIT_LAG=1000
      - JAVA_OPTS=-Djava.locale.providers=JRE,SPI